name: my_website

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - "${PG_DATA_PATH}:/var/lib/postgresql/data"
      - ./src/db/user_db/user_create.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${REDIS_DATA_PATH}:/data"
    command: redis-server --appendonly yes
